# Generated by Django 3.1.1 on 2020-11-07 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('canceled', models.BooleanField(default=False)),
                ('recurrence_period', models.PositiveIntegerField(default=1)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('expires', models.DateField(default=django.utils.timezone.now, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=64)),
                ('transactionID', models.CharField(max_length=100)),
                ('conversationID', models.CharField(max_length=100)),
                ('reference_no', models.CharField(max_length=150)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
