# Generated by Django 3.1.1 on 2020-10-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('price',)},
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
