# Generated by Django 3.1.1 on 2020-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(help_text='Format: 07xxxxxxxx', max_length=10, verbose_name='Enter your M-PESA mobile number'),
        ),
    ]
