# Generated by Django 3.1.1 on 2020-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201001_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrence_period',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
